os:
  - linux
  - osx

dist: bionic

sudo: required
language: generic

env:
  matrix:
    - MODE=unit NET=mainnet
    - MODE=unit NET=testnet
    - MODE=ledger NET=mainnet
    - MODE=ledger NET=testnet

matrix:
  exclude:
    - os: osx
      env: MODE=ledger NET=mainnet
    - os: osx
      env: MODE=ledger NET=testnet

services:
  - docker

before_script:
# Make variables and function from Travis available in our script
# See implementation https://github.com/travis-ci/travis-build/blob/4041ba116ddb3bdfd66ab8acbb7094dee28d6797/lib/travis/build/templates/header.sh
# and http://www.garbers.co.za/2017/11/01/code-folding-and-timing-in-travis-ci/
- export ANSI_CLEAR
- export -f travis_nanoseconds travis_fold travis_time_start travis_time_finish

script:
  - ./scripts/travis.sh

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/

notifications:
  email: false

deploy:
  provider: releases
  api_key:
    secure: "LE+yFnAWvkyTxVk8D/4N+G31Ghja9m3ZxVu8pO6ilEeFk+RsjguDq34bqyEki9pa1KHPgM1oSoz/e4YPqFqEP+oEKuqpZEw0Tl/yRCWu1Mg958PiGN9osgPg36FVHyGa3usRrVI21Agxb+VBJ0l6fzk+XY1YMqV0a1xFHAYj0XJaVKBY5bfyVVzGAzsTUZM1SUzTSbV2CXSVr+1n5XDNIgTeV6whxWdVDsdsXVKeFJ6sBrrRuIkLq4w9hsS5w7Wbs9KBcoEW1ZtjkKKxIs8R3k1S0zcAbQyhrsKL1/+j0LAZYz32O7OjryRnXsu/mIhojiazz4FdU9RUa9l1eh76W+U6hzUkgN8COea4O4IC3UwbAHTi+SDVRwkpFNooCxrpmv67rSzwMtNHDWhGWF0PzBSFF5cGURU6QrWZYdsgkljSTZZKL5SCga0jasl0wf0AzqBHctb76gNtJhfT+kxbPpbrb7zrzZgfU2FW8Pg0lpU0NsLp3DrLVH7sIuzK1urTgO/S8d/A8AQhnBStAqTrWqzvtXIN5iyLgTwBaWdzdnhTKAt5TV7B9rz+lnjwaM5np4+HMr8mXCbrrk8z6X0uDZgX+8ZR/oV5iSkPmgFAIi//d32bLFzKPC9aFMJgJoHPxMSFKDtR3fUCmPZF3gOOuWQnHmP4zfEKsi8NXoBDGfw="
  file_glob: true
  file: exports/*
  skip_cleanup: true
  on:
    tags: true
